# Generated by Django 2.1.7 on 2019-02-14 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(default='', max_length=255)),
                ('lokasi', models.CharField(default='', max_length=255)),
                ('bidang', models.CharField(default='', max_length=255)),
                ('deadline', models.DateField(default=django.utils.timezone.now)),
                ('deskripsi', models.TextField(default='', max_length=10000)),
                ('logo_perusahaan', models.ImageField(upload_to='Media/img')),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('salary', models.IntegerField(default=3000000)),
            ],
        ),
    ]
